apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  annotations:
    tekton.dev/docker-0: https://registry.gitlab.io/v1/
    tekton.dev/git-0: https://gitlab.com
type: kubernetes.io/basic-auth
stringData:
  username: ___GITLAB_USER___
  password: ___GITLAB_TOKEN___
