apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-bookinfo-run-
spec:
  serviceAccountName: tekton-admin
  taskRef:
    name: git-clone
  workspaces:
    - name: output
      volumeClaimTemplate: 
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
  params:
    - name: url
      value: https://gitlab.com/___GITLAB_USER___/bookinfo.git
    - name: revision
      value: main